-- DEMIS Oracle mock schema reconstructed from validated Catalog Package v2.
-- Development/test fixture only. Contains schema metadata only; no patient rows.
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
ALTER SESSION SET CONTAINER=FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA=DEMIS_OWNER;

CREATE TABLE TB_ADM_HIST (
  ADM_ID NUMBER(18,0) NOT NULL,
  ENC_ID NUMBER(18,0) NOT NULL,
  ADM_DT TIMESTAMP(6),
  WARD_CD VARCHAR2(20 CHAR),
  ROOM_NO VARCHAR2(20 CHAR),
  BED_NO VARCHAR2(20 CHAR),
  ADM_RSN_CD VARCHAR2(20 CHAR),
  ADM_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_ADM_HIST PRIMARY KEY (ADM_ID)
);

CREATE TABLE TB_CD_MST (
  CD_GRP_ID VARCHAR2(30 CHAR) NOT NULL,
  CD_VAL VARCHAR2(30 CHAR) NOT NULL,
  CD_NM VARCHAR2(200 CHAR),
  CD_NM_ENG VARCHAR2(200 CHAR),
  USE_YN CHAR(1 CHAR),
  SORT_NO NUMBER(10,0),
  REG_DT TIMESTAMP(6),
  CONSTRAINT PK_TB_CD_MST PRIMARY KEY (CD_GRP_ID, CD_VAL)
);

CREATE TABLE TB_CLN_NOTE (
  NOTE_ID NUMBER(18,0) NOT NULL,
  ENC_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  NOTE_TYP_CD VARCHAR2(20 CHAR),
  NOTE_DT TIMESTAMP(6),
  AUTHOR_DCTR_ID VARCHAR2(30 CHAR),
  NOTE_TITLE VARCHAR2(300 CHAR),
  NOTE_TEXT CLOB,
  NOTE_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_CLN_NOTE PRIMARY KEY (NOTE_ID)
);

CREATE TABLE TB_DCTR_MST (
  DCTR_ID VARCHAR2(30 CHAR) NOT NULL,
  DCTR_NM VARCHAR2(100 CHAR),
  DEPT_CD VARCHAR2(20 CHAR),
  LIC_NO VARCHAR2(50 CHAR),
  SPEC_CD VARCHAR2(20 CHAR),
  USE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_DCTR_MST PRIMARY KEY (DCTR_ID)
);

CREATE TABLE TB_DEPT_MST (
  DEPT_CD VARCHAR2(20 CHAR) NOT NULL,
  DEPT_NM VARCHAR2(200 CHAR) NOT NULL,
  UNIT_ID VARCHAR2(20 CHAR),
  DEPT_TYP_CD VARCHAR2(20 CHAR),
  USE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_DEPT_MST PRIMARY KEY (DEPT_CD)
);

CREATE TABLE TB_DISCH_HIST (
  DISCH_ID NUMBER(18,0) NOT NULL,
  ADM_ID NUMBER(18,0) NOT NULL,
  DISCH_DT TIMESTAMP(6),
  DISCH_TYP_CD VARCHAR2(20 CHAR),
  DISCH_STS_CD VARCHAR2(20 CHAR),
  DISCH_DEPT_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_DISCH_HIST PRIMARY KEY (DISCH_ID)
);

CREATE TABLE TB_DISCH_SUM (
  DISCH_SUM_ID NUMBER(18,0) NOT NULL,
  DISCH_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  ENC_ID NUMBER(18,0) NOT NULL,
  AUTHOR_DCTR_ID VARCHAR2(30 CHAR),
  SUM_DT TIMESTAMP(6),
  ADMIT_DX CLOB,
  DISCH_DX CLOB,
  HOSP_COURSE CLOB,
  DISCH_MED CLOB,
  FOLLOWUP_PLAN CLOB,
  CONSTRAINT PK_TB_DISCH_SUM PRIMARY KEY (DISCH_SUM_ID)
);

CREATE TABLE TB_DX_DTL (
  DX_DTL_ID NUMBER(18,0) NOT NULL,
  DX_ID NUMBER(18,0) NOT NULL,
  DX_ATTR_CD VARCHAR2(30 CHAR),
  DX_ATTR_VAL VARCHAR2(500 CHAR),
  NOTE_TXT VARCHAR2(1000 CHAR),
  CONSTRAINT PK_TB_DX_DTL PRIMARY KEY (DX_DTL_ID)
);

CREATE TABLE TB_DX_HIST (
  DX_ID NUMBER(18,0) NOT NULL,
  ENC_ID NUMBER(18,0) NOT NULL,
  DX_SEQ_NO NUMBER(5,0) NOT NULL,
  DX_CD VARCHAR2(30 CHAR) NOT NULL,
  DX_NM VARCHAR2(300 CHAR),
  DX_TYP_CD VARCHAR2(20 CHAR),
  MAIN_DX_YN CHAR(1 CHAR),
  DX_DT TIMESTAMP(6),
  DCTR_ID VARCHAR2(30 CHAR),
  REG_DT TIMESTAMP(6),
  CONSTRAINT PK_TB_DX_HIST PRIMARY KEY (DX_ID),
  CONSTRAINT UK_DX_ENC_SEQ UNIQUE (ENC_ID, DX_SEQ_NO)
);

CREATE TABLE TB_ENC_HIST (
  ENC_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  ENC_NO VARCHAR2(30 CHAR) NOT NULL,
  ENC_TYP_CD VARCHAR2(20 CHAR),
  DEPT_CD VARCHAR2(20 CHAR),
  DCTR_ID VARCHAR2(30 CHAR),
  ENC_STRT_DT TIMESTAMP(6),
  ENC_END_DT TIMESTAMP(6),
  ENC_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_ENC_HIST PRIMARY KEY (ENC_ID),
  CONSTRAINT UK_TB_ENC_HIST_NO UNIQUE (ENC_NO)
);

CREATE TABLE TB_LAB_ORD (
  LAB_ORD_ID NUMBER(18,0) NOT NULL,
  ORD_DTL_ID NUMBER(18,0),
  ENC_ID NUMBER(18,0) NOT NULL,
  TEST_CD VARCHAR2(40 CHAR),
  TEST_NM VARCHAR2(300 CHAR),
  SPECIMEN_CD VARCHAR2(20 CHAR),
  ORD_DT TIMESTAMP(6),
  COLLECT_DT TIMESTAMP(6),
  LAB_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_LAB_ORD PRIMARY KEY (LAB_ORD_ID)
);

CREATE TABLE TB_LAB_REF (
  LAB_REF_ID NUMBER(18,0) NOT NULL,
  TEST_ITEM_CD VARCHAR2(40 CHAR) NOT NULL,
  SEX_CD CHAR(1 CHAR),
  AGE_FROM NUMBER(5,0),
  AGE_TO NUMBER(5,0),
  REF_LOW NUMBER(20,6),
  REF_HIGH NUMBER(20,6),
  UNIT_CD VARCHAR2(20 CHAR),
  USE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_LAB_REF PRIMARY KEY (LAB_REF_ID)
);

CREATE TABLE TB_LAB_RST (
  LAB_RST_ID NUMBER(18,0) NOT NULL,
  LAB_ORD_ID NUMBER(18,0) NOT NULL,
  RST_SEQ_NO NUMBER(5,0) NOT NULL,
  TEST_ITEM_CD VARCHAR2(40 CHAR),
  TEST_ITEM_NM VARCHAR2(300 CHAR),
  RST_VAL VARCHAR2(200 CHAR),
  RST_NUM NUMBER(20,6),
  UNIT_CD VARCHAR2(20 CHAR),
  REF_LOW NUMBER(20,6),
  REF_HIGH NUMBER(20,6),
  ABN_FLAG_CD VARCHAR2(20 CHAR),
  RST_DT TIMESTAMP(6),
  CONSTRAINT PK_TB_LAB_RST PRIMARY KEY (LAB_RST_ID),
  CONSTRAINT UK_LAB_RST_SEQ UNIQUE (LAB_ORD_ID, RST_SEQ_NO)
);

CREATE TABLE TB_MED_ADM (
  MED_ADM_ID NUMBER(18,0) NOT NULL,
  MED_ORD_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  ADM_DT TIMESTAMP(6),
  DOSE_QTY NUMBER(12,3),
  DOSE_UNIT_CD VARCHAR2(20 CHAR),
  ADM_ROUTE_CD VARCHAR2(20 CHAR),
  ADM_DCTR_ID VARCHAR2(30 CHAR),
  ADM_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_MED_ADM PRIMARY KEY (MED_ADM_ID)
);

CREATE TABLE TB_MED_ORD (
  MED_ORD_ID NUMBER(18,0) NOT NULL,
  ORD_DTL_ID NUMBER(18,0) NOT NULL,
  DRUG_CD VARCHAR2(40 CHAR),
  DRUG_NM VARCHAR2(300 CHAR),
  DOSE_QTY NUMBER(12,3),
  DOSE_UNIT_CD VARCHAR2(20 CHAR),
  ROUTE_CD VARCHAR2(20 CHAR),
  FREQ_CD VARCHAR2(20 CHAR),
  DAYS_NO NUMBER(5,0),
  CONSTRAINT PK_TB_MED_ORD PRIMARY KEY (MED_ORD_ID)
);

CREATE TABLE TB_ORD_DTL (
  ORD_DTL_ID NUMBER(18,0) NOT NULL,
  ORD_ID NUMBER(18,0) NOT NULL,
  ORD_SEQ_NO NUMBER(5,0) NOT NULL,
  ORD_TYP_CD VARCHAR2(20 CHAR),
  ITEM_CD VARCHAR2(40 CHAR),
  ITEM_NM VARCHAR2(300 CHAR),
  QTY NUMBER(12,3),
  UNIT_CD VARCHAR2(20 CHAR),
  FREQ_CD VARCHAR2(20 CHAR),
  START_DT TIMESTAMP(6),
  END_DT TIMESTAMP(6),
  ORD_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_ORD_DTL PRIMARY KEY (ORD_DTL_ID),
  CONSTRAINT UK_ORD_DTL_SEQ UNIQUE (ORD_ID, ORD_SEQ_NO)
);

CREATE TABLE TB_ORD_HDR (
  ORD_ID NUMBER(18,0) NOT NULL,
  ENC_ID NUMBER(18,0) NOT NULL,
  ORD_NO VARCHAR2(30 CHAR) NOT NULL,
  ORD_DT TIMESTAMP(6),
  ORD_DCTR_ID VARCHAR2(30 CHAR),
  ORD_DEPT_CD VARCHAR2(20 CHAR),
  ORD_STS_CD VARCHAR2(20 CHAR),
  URGENT_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_ORD_HDR PRIMARY KEY (ORD_ID),
  CONSTRAINT UK_TB_ORD_HDR_NO UNIQUE (ORD_NO)
);

CREATE TABLE TB_PT_ADDR (
  PT_ADDR_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  ADDR_TYP_CD VARCHAR2(20 CHAR),
  ZIP_CD VARCHAR2(10 CHAR),
  ADDR1 VARCHAR2(300 CHAR),
  ADDR2 VARCHAR2(300 CHAR),
  USE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_PT_ADDR PRIMARY KEY (PT_ADDR_ID)
);

CREATE TABLE TB_PT_CONTACT (
  PT_CONT_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  CONT_TYP_CD VARCHAR2(20 CHAR),
  CONT_VAL VARCHAR2(100 CHAR),
  PRIORITY_NO NUMBER(5,0),
  USE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_PT_CONTACT PRIMARY KEY (PT_CONT_ID)
);

CREATE TABLE TB_PT_MST (
  PT_ID NUMBER(18,0) NOT NULL,
  PT_NO VARCHAR2(30 CHAR) NOT NULL,
  PT_NM VARCHAR2(100 CHAR),
  SEX_CD CHAR(1 CHAR),
  BIRTH_DT DATE,
  SVC_NO VARCHAR2(30 CHAR),
  BLOOD_TYP_CD VARCHAR2(10 CHAR),
  RH_TYP_CD VARCHAR2(5 CHAR),
  PT_STS_CD VARCHAR2(20 CHAR),
  REG_DT TIMESTAMP(6),
  UPD_DT TIMESTAMP(6),
  CONSTRAINT PK_TB_PT_MST PRIMARY KEY (PT_ID),
  CONSTRAINT UK_TB_PT_MST_PT_NO UNIQUE (PT_NO)
);

CREATE TABLE TB_RAD_ORD (
  RAD_ORD_ID NUMBER(18,0) NOT NULL,
  ORD_DTL_ID NUMBER(18,0),
  ENC_ID NUMBER(18,0) NOT NULL,
  MODALITY_CD VARCHAR2(20 CHAR),
  EXAM_CD VARCHAR2(40 CHAR),
  EXAM_NM VARCHAR2(300 CHAR),
  BODY_PART_CD VARCHAR2(30 CHAR),
  ORD_DT TIMESTAMP(6),
  EXAM_DT TIMESTAMP(6),
  RAD_STS_CD VARCHAR2(20 CHAR),
  CONSTRAINT PK_TB_RAD_ORD PRIMARY KEY (RAD_ORD_ID)
);

CREATE TABLE TB_RAD_RPT (
  RAD_RPT_ID NUMBER(18,0) NOT NULL,
  RAD_ORD_ID NUMBER(18,0) NOT NULL,
  RPT_DT TIMESTAMP(6),
  RPT_DCTR_ID VARCHAR2(30 CHAR),
  FINDINGS CLOB,
  IMPRESSION CLOB,
  FINAL_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_RAD_RPT PRIMARY KEY (RAD_RPT_ID)
);

CREATE TABLE TB_SOAP_NOTE (
  SOAP_ID NUMBER(18,0) NOT NULL,
  ENC_ID NUMBER(18,0) NOT NULL,
  PT_ID NUMBER(18,0) NOT NULL,
  AUTHOR_DCTR_ID VARCHAR2(30 CHAR),
  NOTE_DT TIMESTAMP(6),
  SUBJECTIVE CLOB,
  OBJECTIVE CLOB,
  ASSESSMENT CLOB,
  PLAN_TEXT CLOB,
  CONSTRAINT PK_TB_SOAP_NOTE PRIMARY KEY (SOAP_ID)
);

CREATE TABLE TB_SVC_MEMBER (
  SVC_NO VARCHAR2(30 CHAR) NOT NULL,
  UNIT_ID VARCHAR2(20 CHAR),
  RANK_CD VARCHAR2(20 CHAR),
  MIL_SPEC_CD VARCHAR2(20 CHAR),
  ENLIST_DT DATE,
  DISCH_DT DATE,
  ACTIVE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_SVC_MEMBER PRIMARY KEY (SVC_NO)
);

CREATE TABLE TB_UNIT_MST (
  UNIT_ID VARCHAR2(20 CHAR) NOT NULL,
  UNIT_NM VARCHAR2(200 CHAR) NOT NULL,
  UPPER_UNIT_ID VARCHAR2(20 CHAR),
  UNIT_TYP_CD VARCHAR2(20 CHAR),
  USE_YN CHAR(1 CHAR),
  CONSTRAINT PK_TB_UNIT_MST PRIMARY KEY (UNIT_ID)
);

ALTER TABLE TB_ADM_HIST ADD CONSTRAINT FK_ADM_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_CLN_NOTE ADD CONSTRAINT FK_CLN_NOTE_DCTR FOREIGN KEY (AUTHOR_DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_CLN_NOTE ADD CONSTRAINT FK_CLN_NOTE_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_CLN_NOTE ADD CONSTRAINT FK_CLN_NOTE_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_DCTR_MST ADD CONSTRAINT FK_DCTR_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD);
ALTER TABLE TB_DEPT_MST ADD CONSTRAINT FK_DEPT_UNIT FOREIGN KEY (UNIT_ID) REFERENCES TB_UNIT_MST (UNIT_ID);
ALTER TABLE TB_DISCH_HIST ADD CONSTRAINT FK_DISCH_ADM FOREIGN KEY (ADM_ID) REFERENCES TB_ADM_HIST (ADM_ID);
ALTER TABLE TB_DISCH_SUM ADD CONSTRAINT FK_DIS_SUM_DCTR FOREIGN KEY (AUTHOR_DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_DISCH_SUM ADD CONSTRAINT FK_DIS_SUM_DISCH FOREIGN KEY (DISCH_ID) REFERENCES TB_DISCH_HIST (DISCH_ID);
ALTER TABLE TB_DISCH_SUM ADD CONSTRAINT FK_DIS_SUM_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_DISCH_SUM ADD CONSTRAINT FK_DIS_SUM_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_DX_HIST ADD CONSTRAINT FK_DX_DCTR FOREIGN KEY (DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_DX_DTL ADD CONSTRAINT FK_DX_DTL_DX FOREIGN KEY (DX_ID) REFERENCES TB_DX_HIST (DX_ID);
ALTER TABLE TB_DX_HIST ADD CONSTRAINT FK_DX_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_ENC_HIST ADD CONSTRAINT FK_ENC_DCTR FOREIGN KEY (DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_ENC_HIST ADD CONSTRAINT FK_ENC_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD);
ALTER TABLE TB_ENC_HIST ADD CONSTRAINT FK_ENC_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_LAB_ORD ADD CONSTRAINT FK_LAB_ORD_DTL FOREIGN KEY (ORD_DTL_ID) REFERENCES TB_ORD_DTL (ORD_DTL_ID);
ALTER TABLE TB_LAB_ORD ADD CONSTRAINT FK_LAB_ORD_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_LAB_RST ADD CONSTRAINT FK_LAB_RST_ORD FOREIGN KEY (LAB_ORD_ID) REFERENCES TB_LAB_ORD (LAB_ORD_ID);
ALTER TABLE TB_MED_ADM ADD CONSTRAINT FK_MED_ADM_DCTR FOREIGN KEY (ADM_DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_MED_ADM ADD CONSTRAINT FK_MED_ADM_ORD FOREIGN KEY (MED_ORD_ID) REFERENCES TB_MED_ORD (MED_ORD_ID);
ALTER TABLE TB_MED_ADM ADD CONSTRAINT FK_MED_ADM_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_MED_ORD ADD CONSTRAINT FK_MED_ORD_DTL FOREIGN KEY (ORD_DTL_ID) REFERENCES TB_ORD_DTL (ORD_DTL_ID);
ALTER TABLE TB_ORD_DTL ADD CONSTRAINT FK_ORD_DTL_HDR FOREIGN KEY (ORD_ID) REFERENCES TB_ORD_HDR (ORD_ID);
ALTER TABLE TB_ORD_HDR ADD CONSTRAINT FK_ORD_HDR_DCTR FOREIGN KEY (ORD_DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_ORD_HDR ADD CONSTRAINT FK_ORD_HDR_DEPT FOREIGN KEY (ORD_DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD);
ALTER TABLE TB_ORD_HDR ADD CONSTRAINT FK_ORD_HDR_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_PT_ADDR ADD CONSTRAINT FK_PT_ADDR_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_PT_CONTACT ADD CONSTRAINT FK_PT_CONT_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_PT_MST ADD CONSTRAINT FK_PT_SVC FOREIGN KEY (SVC_NO) REFERENCES TB_SVC_MEMBER (SVC_NO);
ALTER TABLE TB_RAD_ORD ADD CONSTRAINT FK_RAD_ORD_DTL FOREIGN KEY (ORD_DTL_ID) REFERENCES TB_ORD_DTL (ORD_DTL_ID);
ALTER TABLE TB_RAD_ORD ADD CONSTRAINT FK_RAD_ORD_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_RAD_RPT ADD CONSTRAINT FK_RAD_RPT_DCTR FOREIGN KEY (RPT_DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_RAD_RPT ADD CONSTRAINT FK_RAD_RPT_ORD FOREIGN KEY (RAD_ORD_ID) REFERENCES TB_RAD_ORD (RAD_ORD_ID);
ALTER TABLE TB_SOAP_NOTE ADD CONSTRAINT FK_SOAP_DCTR FOREIGN KEY (AUTHOR_DCTR_ID) REFERENCES TB_DCTR_MST (DCTR_ID);
ALTER TABLE TB_SOAP_NOTE ADD CONSTRAINT FK_SOAP_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID);
ALTER TABLE TB_SOAP_NOTE ADD CONSTRAINT FK_SOAP_PT FOREIGN KEY (PT_ID) REFERENCES TB_PT_MST (PT_ID);
ALTER TABLE TB_SVC_MEMBER ADD CONSTRAINT FK_SVC_UNIT FOREIGN KEY (UNIT_ID) REFERENCES TB_UNIT_MST (UNIT_ID);
ALTER TABLE TB_UNIT_MST ADD CONSTRAINT FK_UNIT_UPPER FOREIGN KEY (UPPER_UNIT_ID) REFERENCES TB_UNIT_MST (UNIT_ID);

CREATE INDEX IX_ADM_ENC ON TB_ADM_HIST (ENC_ID);
CREATE INDEX IX_CLN_NOTE_ENC_DT ON TB_CLN_NOTE (ENC_ID, NOTE_DT);
CREATE INDEX IX_DISCH_SUM_ENC ON TB_DISCH_SUM (ENC_ID);
CREATE INDEX IX_DX_CD ON TB_DX_HIST (DX_CD);
CREATE INDEX IX_DX_ENC_DT ON TB_DX_HIST (ENC_ID, DX_DT);
CREATE INDEX IX_ENC_DEPT ON TB_ENC_HIST (DEPT_CD);
CREATE INDEX IX_ENC_PT_DT ON TB_ENC_HIST (PT_ID, ENC_STRT_DT);
CREATE INDEX IX_LAB_ORD_ENC ON TB_LAB_ORD (ENC_ID);
CREATE INDEX IX_LAB_RST_ITEM ON TB_LAB_RST (TEST_ITEM_CD);
CREATE INDEX IX_LAB_RST_ORD ON TB_LAB_RST (LAB_ORD_ID);
CREATE INDEX IX_MED_ADM_ORD_DT ON TB_MED_ADM (MED_ORD_ID, ADM_DT);
CREATE INDEX IX_MED_ORD_DTL ON TB_MED_ORD (ORD_DTL_ID);
CREATE INDEX IX_ORD_DTL_ORD ON TB_ORD_DTL (ORD_ID);
CREATE INDEX IX_ORD_ENC_DT ON TB_ORD_HDR (ENC_ID, ORD_DT);
CREATE INDEX IX_PT_ADDR_PT ON TB_PT_ADDR (PT_ID);
CREATE INDEX IX_PT_CONTACT_PT ON TB_PT_CONTACT (PT_ID);
CREATE INDEX IX_RAD_ORD_ENC ON TB_RAD_ORD (ENC_ID);
CREATE INDEX IX_RAD_RPT_ORD ON TB_RAD_RPT (RAD_ORD_ID);
CREATE INDEX IX_SOAP_ENC_DT ON TB_SOAP_NOTE (ENC_ID, NOTE_DT);

COMMENT ON TABLE TB_ADM_HIST IS '환자 입원 이력';
COMMENT ON TABLE TB_CD_MST IS '공통 코드 마스터';
COMMENT ON TABLE TB_CLN_NOTE IS '임상 진료기록 정보';
COMMENT ON TABLE TB_DCTR_MST IS '의료진 마스터';
COMMENT ON TABLE TB_DEPT_MST IS '진료과 마스터';
COMMENT ON TABLE TB_DISCH_HIST IS '환자 퇴원 이력';
COMMENT ON TABLE TB_DISCH_SUM IS '퇴원 요약 기록 정보';
COMMENT ON TABLE TB_DX_DTL IS '환자 진단 상세 정보';
COMMENT ON TABLE TB_DX_HIST IS '환자 진단 이력';
COMMENT ON TABLE TB_ENC_HIST IS '환자 진료 이력';
COMMENT ON TABLE TB_LAB_ORD IS '임상검사 오더 정보';
COMMENT ON TABLE TB_LAB_REF IS '임상검사 정상 참고범위 정보';
COMMENT ON TABLE TB_LAB_RST IS '임상검사 결과 정보';
COMMENT ON TABLE TB_MED_ADM IS '환자 약제 투약 이력';
COMMENT ON TABLE TB_MED_ORD IS '환자 약제 처방 정보';
COMMENT ON TABLE TB_ORD_DTL IS '진료 오더 상세 정보';
COMMENT ON TABLE TB_ORD_HDR IS '진료 오더 기본 정보';
COMMENT ON TABLE TB_PT_ADDR IS '환자 주소 정보';
COMMENT ON TABLE TB_PT_CONTACT IS '환자 연락처 정보';
COMMENT ON TABLE TB_PT_MST IS '환자 기본 정보';
COMMENT ON TABLE TB_RAD_ORD IS '영상검사 오더 정보';
COMMENT ON TABLE TB_RAD_RPT IS '영상검사 판독 결과 정보';
COMMENT ON TABLE TB_SOAP_NOTE IS 'SOAP 진료기록 정보';
COMMENT ON TABLE TB_SVC_MEMBER IS '군 복무자 기본 정보';
COMMENT ON TABLE TB_UNIT_MST IS '군 부대 마스터';

COMMENT ON COLUMN TB_ADM_HIST.WARD_CD IS '입원 병동 코드';
COMMENT ON COLUMN TB_DX_HIST.DX_CD IS '진단 코드';
COMMENT ON COLUMN TB_DX_HIST.MAIN_DX_YN IS '주진단 여부';
COMMENT ON COLUMN TB_ENC_HIST.ENC_ID IS '진료 Encounter 식별자';
COMMENT ON COLUMN TB_ENC_HIST.ENC_TYP_CD IS '진료 유형 코드';
COMMENT ON COLUMN TB_ENC_HIST.DCTR_ID IS '진료 담당 의료진 식별자';
COMMENT ON COLUMN TB_LAB_RST.ABN_FLAG_CD IS '검사결과 이상 여부 코드';
COMMENT ON COLUMN TB_MED_ORD.ROUTE_CD IS '투약 경로 코드';
COMMENT ON COLUMN TB_PT_MST.PT_ID IS '환자 내부 식별자';
COMMENT ON COLUMN TB_PT_MST.PT_NO IS '환자 번호';
COMMENT ON COLUMN TB_PT_MST.SVC_NO IS '군 복무 식별번호';
COMMENT ON COLUMN TB_RAD_RPT.FINDINGS IS '영상검사 주요 소견';
COMMENT ON COLUMN TB_RAD_RPT.IMPRESSION IS '영상검사 판독 결론';

ALTER SESSION SET CURRENT_SCHEMA=SYS;
GRANT SELECT ON DEMIS_OWNER.TB_ADM_HIST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_CD_MST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_CLN_NOTE TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_DCTR_MST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_DEPT_MST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_DISCH_HIST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_DISCH_SUM TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_DX_DTL TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_DX_HIST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_ENC_HIST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_LAB_ORD TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_LAB_REF TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_LAB_RST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_MED_ADM TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_MED_ORD TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_ORD_DTL TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_ORD_HDR TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_PT_ADDR TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_PT_CONTACT TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_PT_MST TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_RAD_ORD TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_RAD_RPT TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_SOAP_NOTE TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_SVC_MEMBER TO DEMIS_RO;
GRANT SELECT ON DEMIS_OWNER.TB_UNIT_MST TO DEMIS_RO;

EXIT;
