-- ============================================================
-- medical_demo schema (DEMIS Mock Medical DB)
-- Idempotent-friendly: DROP IF EXISTS then CREATE
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- Drop in dependency order (children first)
DROP TABLE IF EXISTS TB_LAB_RST CASCADE;
DROP TABLE IF EXISTS TB_LAB_ORD CASCADE;
DROP TABLE IF EXISTS TB_LAB_REF CASCADE;
DROP TABLE IF EXISTS TB_MED_ORD CASCADE;
DROP TABLE IF EXISTS TB_IMG_RPT CASCADE;
DROP TABLE IF EXISTS TB_IMG_ORD CASCADE;
DROP TABLE IF EXISTS TB_CLN_DOC CASCADE;
DROP TABLE IF EXISTS TB_ORD_DTL CASCADE;
DROP TABLE IF EXISTS TB_ORD_HDR CASCADE;
DROP TABLE IF EXISTS TB_DGN_HIST CASCADE;
DROP TABLE IF EXISTS TB_PROC_HIST CASCADE;
DROP TABLE IF EXISTS TB_ADM_HIST CASCADE;
DROP TABLE IF EXISTS TB_ENC_HIST CASCADE;
DROP TABLE IF EXISTS TB_PT_MST CASCADE;
DROP TABLE IF EXISTS TB_PROVIDER CASCADE;
DROP TABLE IF EXISTS TB_DEPT_MST CASCADE;
DROP TABLE IF EXISTS TB_WARD_MST CASCADE;
DROP TABLE IF EXISTS TB_DOC_TYPE CASCADE;
DROP TABLE IF EXISTS TB_LAB_MST CASCADE;
DROP TABLE IF EXISTS TB_DRUG_MST CASCADE;
DROP TABLE IF EXISTS TB_PROC_MST CASCADE;
DROP TABLE IF EXISTS TB_DGN_CD_MST CASCADE;
DROP TABLE IF EXISTS TB_CODE_MST CASCADE;
DROP TABLE IF EXISTS TB_IMG_MST CASCADE;

-- ------------------------------------------------------------
-- Master / Code tables
-- ------------------------------------------------------------

CREATE TABLE TB_CODE_MST (
    CD_GRP       VARCHAR(20)  NOT NULL,
    CD_VAL       VARCHAR(20)  NOT NULL,
    CD_NM        VARCHAR(100) NOT NULL,
    CD_DESC      VARCHAR(300),
    SORT_ORD     INTEGER      NOT NULL DEFAULT 0,
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_CODE_MST PRIMARY KEY (CD_GRP, CD_VAL)
);

CREATE TABLE TB_DEPT_MST (
    DEPT_CD      VARCHAR(10)  NOT NULL,
    DEPT_NM      VARCHAR(100) NOT NULL,
    DEPT_TYP     VARCHAR(20)  NOT NULL,
    UP_DEPT_CD   VARCHAR(10),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_DEPT_MST PRIMARY KEY (DEPT_CD),
    CONSTRAINT FK_DEPT_UP FOREIGN KEY (UP_DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD)
);

CREATE TABLE TB_WARD_MST (
    WARD_CD      VARCHAR(10)  NOT NULL,
    WARD_NM      VARCHAR(100) NOT NULL,
    BED_CNT      INTEGER      NOT NULL DEFAULT 0,
    DEPT_CD      VARCHAR(10),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_WARD_MST PRIMARY KEY (WARD_CD),
    CONSTRAINT FK_WARD_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD)
);

CREATE TABLE TB_PROVIDER (
    PROV_ID      VARCHAR(20)  NOT NULL,
    PROV_NM      VARCHAR(100) NOT NULL,
    PROV_TYP     VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(10)  NOT NULL,
    LIC_NO       VARCHAR(30),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PROVIDER PRIMARY KEY (PROV_ID),
    CONSTRAINT FK_PROV_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD)
);

CREATE TABLE TB_DGN_CD_MST (
    DGN_CD       VARCHAR(20)  NOT NULL,
    DGN_NM       VARCHAR(200) NOT NULL,
    DGN_NM_EN    VARCHAR(200),
    ICD_VER      VARCHAR(10)  NOT NULL DEFAULT 'KCD8',
    CAT_CD       VARCHAR(20),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_DGN_CD_MST PRIMARY KEY (DGN_CD)
);

CREATE TABLE TB_LAB_MST (
    EXM_CD       VARCHAR(20)  NOT NULL,
    EXM_NM       VARCHAR(150) NOT NULL,
    EXM_NM_EN    VARCHAR(150),
    EXM_CAT      VARCHAR(30)  NOT NULL,
    SPEC_TYP     VARCHAR(30),
    UNIT_CD      VARCHAR(20),
    METHOD_CD    VARCHAR(30),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_LAB_MST PRIMARY KEY (EXM_CD)
);

CREATE TABLE TB_LAB_REF (
    REF_ID       BIGSERIAL    NOT NULL,
    EXM_CD       VARCHAR(20)  NOT NULL,
    SEX_CD       CHAR(1)      NOT NULL DEFAULT 'A',
    AGE_FROM     INTEGER      NOT NULL DEFAULT 0,
    AGE_TO       INTEGER      NOT NULL DEFAULT 150,
    LOW_VAL      NUMERIC(12,4),
    HIGH_VAL     NUMERIC(12,4),
    REF_TXT      VARCHAR(100),
    UNIT_CD      VARCHAR(20),
    CONSTRAINT PK_TB_LAB_REF PRIMARY KEY (REF_ID),
    CONSTRAINT FK_LAB_REF_MST FOREIGN KEY (EXM_CD) REFERENCES TB_LAB_MST (EXM_CD)
);

CREATE TABLE TB_DRUG_MST (
    DRUG_CD      VARCHAR(20)  NOT NULL,
    DRUG_NM      VARCHAR(200) NOT NULL,
    GEN_NM       VARCHAR(200),
    ATC_CD       VARCHAR(20),
    FORM_CD      VARCHAR(20),
    STR_VAL      VARCHAR(50),
    UNIT_CD      VARCHAR(20),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_DRUG_MST PRIMARY KEY (DRUG_CD)
);

CREATE TABLE TB_IMG_MST (
    IMG_CD       VARCHAR(20)  NOT NULL,
    IMG_NM       VARCHAR(150) NOT NULL,
    MODALITY     VARCHAR(20)  NOT NULL,
    BODY_PART    VARCHAR(50),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_IMG_MST PRIMARY KEY (IMG_CD)
);

CREATE TABLE TB_PROC_MST (
    PROC_CD      VARCHAR(20)  NOT NULL,
    PROC_NM      VARCHAR(200) NOT NULL,
    PROC_CAT     VARCHAR(30),
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_PROC_MST PRIMARY KEY (PROC_CD)
);

CREATE TABLE TB_DOC_TYPE (
    DOC_TYP_CD   VARCHAR(20)  NOT NULL,
    DOC_TYP_NM   VARCHAR(100) NOT NULL,
    DOC_CAT      VARCHAR(30)  NOT NULL,
    USE_YN       CHAR(1)      NOT NULL DEFAULT 'Y',
    CONSTRAINT PK_TB_DOC_TYPE PRIMARY KEY (DOC_TYP_CD)
);

-- ------------------------------------------------------------
-- Patient / Encounter
-- ------------------------------------------------------------

CREATE TABLE TB_PT_MST (
    PT_NO        VARCHAR(20)  NOT NULL,
    PT_NM        VARCHAR(100) NOT NULL,
    BRTH_DT      DATE         NOT NULL,
    SEX_CD       CHAR(1)      NOT NULL,
    RR_NO_HASH   VARCHAR(64),
    TEL_NO       VARCHAR(20),
    ADDR_TXT     VARCHAR(300),
    BLD_TYP      VARCHAR(5),
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_PT_MST PRIMARY KEY (PT_NO),
    CONSTRAINT CK_PT_SEX CHECK (SEX_CD IN ('M', 'F', 'U'))
);

CREATE TABLE TB_ENC_HIST (
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    ENC_TYP      VARCHAR(10)  NOT NULL,
    ENC_STS      VARCHAR(10)  NOT NULL,
    DEPT_CD      VARCHAR(10)  NOT NULL,
    PROV_ID      VARCHAR(20)  NOT NULL,
    ADM_DT       TIMESTAMP    NOT NULL,
    DSCH_DT      TIMESTAMP,
    CHIEF_COMP   VARCHAR(500),
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_ENC_HIST PRIMARY KEY (ENC_ID),
    CONSTRAINT FK_ENC_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_ENC_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD),
    CONSTRAINT FK_ENC_PROV FOREIGN KEY (PROV_ID) REFERENCES TB_PROVIDER (PROV_ID),
    CONSTRAINT CK_ENC_TYP CHECK (ENC_TYP IN ('O', 'I', 'E')),
    CONSTRAINT CK_ENC_STS CHECK (ENC_STS IN ('A', 'D', 'C'))
);

CREATE TABLE TB_ADM_HIST (
    ADM_ID       VARCHAR(30)  NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    WARD_CD      VARCHAR(10)  NOT NULL,
    BED_NO       VARCHAR(10),
    ADM_DT       TIMESTAMP    NOT NULL,
    DSCH_DT      TIMESTAMP,
    DSCH_TYP     VARCHAR(20),
    ADM_PATH     VARCHAR(20),
    CONSTRAINT PK_TB_ADM_HIST PRIMARY KEY (ADM_ID),
    CONSTRAINT FK_ADM_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_ADM_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_ADM_WARD FOREIGN KEY (WARD_CD) REFERENCES TB_WARD_MST (WARD_CD),
    CONSTRAINT UQ_ADM_ENC UNIQUE (ENC_ID)
);

-- ------------------------------------------------------------
-- Diagnosis / Procedure
-- ------------------------------------------------------------

CREATE TABLE TB_DGN_HIST (
    DGN_ID       BIGSERIAL    NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    DGN_CD       VARCHAR(20)  NOT NULL,
    DGN_SEQ      INTEGER      NOT NULL DEFAULT 1,
    DGN_TYP      VARCHAR(10)  NOT NULL DEFAULT 'MAIN',
    ONSET_DT     DATE,
    DGN_DT       TIMESTAMP    NOT NULL,
    PROV_ID      VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_TB_DGN_HIST PRIMARY KEY (DGN_ID),
    CONSTRAINT FK_DGN_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_DGN_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_DGN_CD FOREIGN KEY (DGN_CD) REFERENCES TB_DGN_CD_MST (DGN_CD),
    CONSTRAINT FK_DGN_PROV FOREIGN KEY (PROV_ID) REFERENCES TB_PROVIDER (PROV_ID)
);

CREATE TABLE TB_PROC_HIST (
    PROC_ID      BIGSERIAL    NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    PROC_CD      VARCHAR(20)  NOT NULL,
    PROC_DT      TIMESTAMP    NOT NULL,
    PROV_ID      VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(10)  NOT NULL,
    PROC_STS     VARCHAR(10)  NOT NULL DEFAULT 'DONE',
    RMRK_TXT     VARCHAR(300),
    CONSTRAINT PK_TB_PROC_HIST PRIMARY KEY (PROC_ID),
    CONSTRAINT FK_PROC_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_PROC_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_PROC_CD FOREIGN KEY (PROC_CD) REFERENCES TB_PROC_MST (PROC_CD),
    CONSTRAINT FK_PROC_PROV FOREIGN KEY (PROV_ID) REFERENCES TB_PROVIDER (PROV_ID),
    CONSTRAINT FK_PROC_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD)
);

-- ------------------------------------------------------------
-- Orders
-- ------------------------------------------------------------

CREATE TABLE TB_ORD_HDR (
    ORD_NO       VARCHAR(30)  NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    ORD_TYP      VARCHAR(10)  NOT NULL,
    ORD_STS      VARCHAR(10)  NOT NULL,
    ORD_DT       TIMESTAMP    NOT NULL,
    PROV_ID      VARCHAR(20)  NOT NULL,
    DEPT_CD      VARCHAR(10)  NOT NULL,
    REG_DT       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_TB_ORD_HDR PRIMARY KEY (ORD_NO),
    CONSTRAINT FK_ORD_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_ORD_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_ORD_PROV FOREIGN KEY (PROV_ID) REFERENCES TB_PROVIDER (PROV_ID),
    CONSTRAINT FK_ORD_DEPT FOREIGN KEY (DEPT_CD) REFERENCES TB_DEPT_MST (DEPT_CD),
    CONSTRAINT CK_ORD_TYP CHECK (ORD_TYP IN ('LAB', 'MED', 'IMG', 'PROC', 'ETC'))
);

CREATE TABLE TB_ORD_DTL (
    ORD_DTL_ID   BIGSERIAL    NOT NULL,
    ORD_NO       VARCHAR(30)  NOT NULL,
    ORD_SEQ      INTEGER      NOT NULL,
    ORD_CD       VARCHAR(20)  NOT NULL,
    ORD_NM       VARCHAR(200) NOT NULL,
    QTY_VAL      NUMERIC(12,2) NOT NULL DEFAULT 1,
    UNIT_CD      VARCHAR(20),
    ORD_STS      VARCHAR(10)  NOT NULL DEFAULT 'ORD',
    CONSTRAINT PK_TB_ORD_DTL PRIMARY KEY (ORD_DTL_ID),
    CONSTRAINT FK_ORD_DTL_HDR FOREIGN KEY (ORD_NO) REFERENCES TB_ORD_HDR (ORD_NO),
    CONSTRAINT UQ_ORD_DTL UNIQUE (ORD_NO, ORD_SEQ)
);

CREATE TABLE TB_LAB_ORD (
    LAB_ORD_ID   BIGSERIAL    NOT NULL,
    ORD_NO       VARCHAR(30)  NOT NULL,
    ORD_DTL_ID   BIGINT       NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    EXM_CD       VARCHAR(20)  NOT NULL,
    SPC_NO       VARCHAR(30),
    COLL_DT      TIMESTAMP,
    ORD_STS      VARCHAR(10)  NOT NULL DEFAULT 'ORD',
    CONSTRAINT PK_TB_LAB_ORD PRIMARY KEY (LAB_ORD_ID),
    CONSTRAINT FK_LAB_ORD_HDR FOREIGN KEY (ORD_NO) REFERENCES TB_ORD_HDR (ORD_NO),
    CONSTRAINT FK_LAB_ORD_DTL FOREIGN KEY (ORD_DTL_ID) REFERENCES TB_ORD_DTL (ORD_DTL_ID),
    CONSTRAINT FK_LAB_ORD_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_LAB_ORD_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_LAB_ORD_EXM FOREIGN KEY (EXM_CD) REFERENCES TB_LAB_MST (EXM_CD)
);

CREATE TABLE TB_LAB_RST (
    LAB_RST_ID   BIGSERIAL    NOT NULL,
    LAB_ORD_ID   BIGINT       NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    EXM_CD       VARCHAR(20)  NOT NULL,
    RST_VAL      VARCHAR(100),
    RST_NUM      NUMERIC(14,4),
    RST_UNIT     VARCHAR(20),
    ABN_FLG      CHAR(1)      NOT NULL DEFAULT 'N',
    RST_DT       TIMESTAMP    NOT NULL,
    RPT_PROV_ID  VARCHAR(20),
    CONSTRAINT PK_TB_LAB_RST PRIMARY KEY (LAB_RST_ID),
    CONSTRAINT FK_LAB_RST_ORD FOREIGN KEY (LAB_ORD_ID) REFERENCES TB_LAB_ORD (LAB_ORD_ID),
    CONSTRAINT FK_LAB_RST_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_LAB_RST_EXM FOREIGN KEY (EXM_CD) REFERENCES TB_LAB_MST (EXM_CD),
    CONSTRAINT FK_LAB_RST_PROV FOREIGN KEY (RPT_PROV_ID) REFERENCES TB_PROVIDER (PROV_ID),
    CONSTRAINT UQ_LAB_RST_ORD UNIQUE (LAB_ORD_ID)
);

CREATE TABLE TB_MED_ORD (
    MED_ORD_ID   BIGSERIAL    NOT NULL,
    ORD_NO       VARCHAR(30)  NOT NULL,
    ORD_DTL_ID   BIGINT       NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    DRUG_CD      VARCHAR(20)  NOT NULL,
    DOSE_VAL     NUMERIC(12,3) NOT NULL,
    DOSE_UNIT    VARCHAR(20)  NOT NULL,
    FREQ_CD      VARCHAR(20)  NOT NULL,
    DAYS_CNT     INTEGER      NOT NULL DEFAULT 1,
    ROUTE_CD     VARCHAR(20)  NOT NULL,
    START_DT     TIMESTAMP    NOT NULL,
    END_DT       TIMESTAMP,
    ORD_STS      VARCHAR(10)  NOT NULL DEFAULT 'ORD',
    CONSTRAINT PK_TB_MED_ORD PRIMARY KEY (MED_ORD_ID),
    CONSTRAINT FK_MED_ORD_HDR FOREIGN KEY (ORD_NO) REFERENCES TB_ORD_HDR (ORD_NO),
    CONSTRAINT FK_MED_ORD_DTL FOREIGN KEY (ORD_DTL_ID) REFERENCES TB_ORD_DTL (ORD_DTL_ID),
    CONSTRAINT FK_MED_ORD_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_MED_ORD_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_MED_ORD_DRUG FOREIGN KEY (DRUG_CD) REFERENCES TB_DRUG_MST (DRUG_CD)
);

CREATE TABLE TB_IMG_ORD (
    IMG_ORD_ID   BIGSERIAL    NOT NULL,
    ORD_NO       VARCHAR(30)  NOT NULL,
    ORD_DTL_ID   BIGINT       NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    IMG_CD       VARCHAR(20)  NOT NULL,
    ACC_NO       VARCHAR(30),
    ORD_DT       TIMESTAMP    NOT NULL,
    PERF_DT      TIMESTAMP,
    ORD_STS      VARCHAR(10)  NOT NULL DEFAULT 'ORD',
    CONSTRAINT PK_TB_IMG_ORD PRIMARY KEY (IMG_ORD_ID),
    CONSTRAINT FK_IMG_ORD_HDR FOREIGN KEY (ORD_NO) REFERENCES TB_ORD_HDR (ORD_NO),
    CONSTRAINT FK_IMG_ORD_DTL FOREIGN KEY (ORD_DTL_ID) REFERENCES TB_ORD_DTL (ORD_DTL_ID),
    CONSTRAINT FK_IMG_ORD_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_IMG_ORD_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_IMG_ORD_CD FOREIGN KEY (IMG_CD) REFERENCES TB_IMG_MST (IMG_CD)
);

CREATE TABLE TB_IMG_RPT (
    IMG_RPT_ID   BIGSERIAL    NOT NULL,
    IMG_ORD_ID   BIGINT       NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    RPT_DT       TIMESTAMP    NOT NULL,
    RPT_PROV_ID  VARCHAR(20)  NOT NULL,
    FIND_TXT     TEXT         NOT NULL,
    IMPR_TXT     TEXT,
    RPT_STS      VARCHAR(10)  NOT NULL DEFAULT 'FINAL',
    CONSTRAINT PK_TB_IMG_RPT PRIMARY KEY (IMG_RPT_ID),
    CONSTRAINT FK_IMG_RPT_ORD FOREIGN KEY (IMG_ORD_ID) REFERENCES TB_IMG_ORD (IMG_ORD_ID),
    CONSTRAINT FK_IMG_RPT_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_IMG_RPT_PROV FOREIGN KEY (RPT_PROV_ID) REFERENCES TB_PROVIDER (PROV_ID),
    CONSTRAINT UQ_IMG_RPT_ORD UNIQUE (IMG_ORD_ID)
);

CREATE TABLE TB_CLN_DOC (
    DOC_ID       VARCHAR(30)  NOT NULL,
    ENC_ID       VARCHAR(30)  NOT NULL,
    PT_NO        VARCHAR(20)  NOT NULL,
    DOC_TYP_CD   VARCHAR(20)  NOT NULL,
    DOC_TTL      VARCHAR(200) NOT NULL,
    DOC_BODY     TEXT         NOT NULL,
    AUTH_PROV_ID VARCHAR(20)  NOT NULL,
    DOC_DT       TIMESTAMP    NOT NULL,
    DOC_STS      VARCHAR(10)  NOT NULL DEFAULT 'SIGNED',
    CONSTRAINT PK_TB_CLN_DOC PRIMARY KEY (DOC_ID),
    CONSTRAINT FK_CLN_DOC_ENC FOREIGN KEY (ENC_ID) REFERENCES TB_ENC_HIST (ENC_ID),
    CONSTRAINT FK_CLN_DOC_PT FOREIGN KEY (PT_NO) REFERENCES TB_PT_MST (PT_NO),
    CONSTRAINT FK_CLN_DOC_TYP FOREIGN KEY (DOC_TYP_CD) REFERENCES TB_DOC_TYPE (DOC_TYP_CD),
    CONSTRAINT FK_CLN_DOC_PROV FOREIGN KEY (AUTH_PROV_ID) REFERENCES TB_PROVIDER (PROV_ID)
);
