-- ============================================================
-- Table / Column comments for medical_demo
-- Future Schema Analyzer will collect these comments.
-- ============================================================

-- TB_CODE_MST
COMMENT ON TABLE TB_CODE_MST IS '공통 코드 마스터. 성별, 상태, 빈도 등 시스템 공통 코드를 관리한다.';
COMMENT ON COLUMN TB_CODE_MST.CD_GRP IS '코드그룹';
COMMENT ON COLUMN TB_CODE_MST.CD_VAL IS '코드값';
COMMENT ON COLUMN TB_CODE_MST.CD_NM IS '코드명';
COMMENT ON COLUMN TB_CODE_MST.CD_DESC IS '코드설명';
COMMENT ON COLUMN TB_CODE_MST.SORT_ORD IS '정렬순서';
COMMENT ON COLUMN TB_CODE_MST.USE_YN IS '사용여부(Y/N)';
COMMENT ON COLUMN TB_CODE_MST.REG_DT IS '등록일시';

-- TB_DEPT_MST
COMMENT ON TABLE TB_DEPT_MST IS '진료과/부서 마스터. 내과, 외과, 영상의학과 등 병원 조직 정보를 관리한다.';
COMMENT ON COLUMN TB_DEPT_MST.DEPT_CD IS '진료과코드';
COMMENT ON COLUMN TB_DEPT_MST.DEPT_NM IS '진료과명';
COMMENT ON COLUMN TB_DEPT_MST.DEPT_TYP IS '진료과유형(CLINIC/SUPPORT/ADMIN)';
COMMENT ON COLUMN TB_DEPT_MST.UP_DEPT_CD IS '상위진료과코드';
COMMENT ON COLUMN TB_DEPT_MST.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_DEPT_MST.REG_DT IS '등록일시';

-- TB_WARD_MST
COMMENT ON TABLE TB_WARD_MST IS '병동 마스터. 입원 환자의 병동/병상 운영 정보를 관리한다.';
COMMENT ON COLUMN TB_WARD_MST.WARD_CD IS '병동코드';
COMMENT ON COLUMN TB_WARD_MST.WARD_NM IS '병동명';
COMMENT ON COLUMN TB_WARD_MST.BED_CNT IS '병상 수';
COMMENT ON COLUMN TB_WARD_MST.DEPT_CD IS '관련 진료과코드';
COMMENT ON COLUMN TB_WARD_MST.USE_YN IS '사용여부';

-- TB_PROVIDER
COMMENT ON TABLE TB_PROVIDER IS '의료진 마스터. 의사, 간호사 등 의료 제공자 기본정보를 관리한다.';
COMMENT ON COLUMN TB_PROVIDER.PROV_ID IS '의료진ID';
COMMENT ON COLUMN TB_PROVIDER.PROV_NM IS '의료진명';
COMMENT ON COLUMN TB_PROVIDER.PROV_TYP IS '의료진유형(PHYS/NURS/TECH)';
COMMENT ON COLUMN TB_PROVIDER.DEPT_CD IS '소속진료과코드';
COMMENT ON COLUMN TB_PROVIDER.LIC_NO IS '면허번호';
COMMENT ON COLUMN TB_PROVIDER.USE_YN IS '사용여부';
COMMENT ON COLUMN TB_PROVIDER.REG_DT IS '등록일시';

-- TB_DGN_CD_MST
COMMENT ON TABLE TB_DGN_CD_MST IS '진단코드 마스터. KCD/ICD 기반 진단 코드와 명칭을 관리한다.';
COMMENT ON COLUMN TB_DGN_CD_MST.DGN_CD IS '진단코드';
COMMENT ON COLUMN TB_DGN_CD_MST.DGN_NM IS '진단명(한글)';
COMMENT ON COLUMN TB_DGN_CD_MST.DGN_NM_EN IS '진단명(영문)';
COMMENT ON COLUMN TB_DGN_CD_MST.ICD_VER IS 'ICD/KCD 버전';
COMMENT ON COLUMN TB_DGN_CD_MST.CAT_CD IS '진단분류코드';
COMMENT ON COLUMN TB_DGN_CD_MST.USE_YN IS '사용여부';

-- TB_LAB_MST
COMMENT ON TABLE TB_LAB_MST IS '임상검사 항목 마스터. 검사코드, 한글·영문 검사명, 검사분류, 검체유형, 결과단위 및 검사방법을 관리한다.';
COMMENT ON COLUMN TB_LAB_MST.EXM_CD IS '검사코드';
COMMENT ON COLUMN TB_LAB_MST.EXM_NM IS '검사명(한글)';
COMMENT ON COLUMN TB_LAB_MST.EXM_NM_EN IS '검사명(영문)';
COMMENT ON COLUMN TB_LAB_MST.EXM_CAT IS '검사분류(LIVER/GLUCOSE/KIDNEY/CBC/ETC)';
COMMENT ON COLUMN TB_LAB_MST.SPEC_TYP IS '검체유형';
COMMENT ON COLUMN TB_LAB_MST.UNIT_CD IS '결과단위코드';
COMMENT ON COLUMN TB_LAB_MST.METHOD_CD IS '검사방법코드';
COMMENT ON COLUMN TB_LAB_MST.USE_YN IS '사용여부';

-- TB_LAB_REF
COMMENT ON TABLE TB_LAB_REF IS '검사 기준치(참고치) 테이블. 성별·연령별 정상 범위 하한/상한을 관리한다.';
COMMENT ON COLUMN TB_LAB_REF.REF_ID IS '기준치ID';
COMMENT ON COLUMN TB_LAB_REF.EXM_CD IS '검사코드';
COMMENT ON COLUMN TB_LAB_REF.SEX_CD IS '적용성별(A/M/F)';
COMMENT ON COLUMN TB_LAB_REF.AGE_FROM IS '적용연령시작';
COMMENT ON COLUMN TB_LAB_REF.AGE_TO IS '적용연령종료';
COMMENT ON COLUMN TB_LAB_REF.LOW_VAL IS '참고치하한';
COMMENT ON COLUMN TB_LAB_REF.HIGH_VAL IS '참고치상한';
COMMENT ON COLUMN TB_LAB_REF.REF_TXT IS '참고치텍스트';
COMMENT ON COLUMN TB_LAB_REF.UNIT_CD IS '단위코드';

-- TB_DRUG_MST
COMMENT ON TABLE TB_DRUG_MST IS '약품 마스터. 처방 가능한 의약품 코드, 성분명, 제형을 관리한다.';
COMMENT ON COLUMN TB_DRUG_MST.DRUG_CD IS '약품코드';
COMMENT ON COLUMN TB_DRUG_MST.DRUG_NM IS '약품명';
COMMENT ON COLUMN TB_DRUG_MST.GEN_NM IS '성분명';
COMMENT ON COLUMN TB_DRUG_MST.ATC_CD IS 'ATC코드';
COMMENT ON COLUMN TB_DRUG_MST.FORM_CD IS '제형코드';
COMMENT ON COLUMN TB_DRUG_MST.STR_VAL IS '함량';
COMMENT ON COLUMN TB_DRUG_MST.UNIT_CD IS '단위코드';
COMMENT ON COLUMN TB_DRUG_MST.USE_YN IS '사용여부';

-- TB_IMG_MST
COMMENT ON TABLE TB_IMG_MST IS '영상검사 항목 마스터. CT/MRI/X-ray 등 영상 검사 코드를 관리한다.';
COMMENT ON COLUMN TB_IMG_MST.IMG_CD IS '영상검사코드';
COMMENT ON COLUMN TB_IMG_MST.IMG_NM IS '영상검사명';
COMMENT ON COLUMN TB_IMG_MST.MODALITY IS '영상모달리티(CT/MR/XR/US)';
COMMENT ON COLUMN TB_IMG_MST.BODY_PART IS '촬영부위';
COMMENT ON COLUMN TB_IMG_MST.USE_YN IS '사용여부';

-- TB_PROC_MST
COMMENT ON TABLE TB_PROC_MST IS '처치/시술 마스터. 의료 처치 및 시술 코드와 명칭을 관리한다.';
COMMENT ON COLUMN TB_PROC_MST.PROC_CD IS '처치시술코드';
COMMENT ON COLUMN TB_PROC_MST.PROC_NM IS '처치시술명';
COMMENT ON COLUMN TB_PROC_MST.PROC_CAT IS '처치분류';
COMMENT ON COLUMN TB_PROC_MST.USE_YN IS '사용여부';

-- TB_DOC_TYPE
COMMENT ON TABLE TB_DOC_TYPE IS '임상문서 유형 마스터. 퇴원요약, 경과기록 등 문서유형을 관리한다.';
COMMENT ON COLUMN TB_DOC_TYPE.DOC_TYP_CD IS '문서유형코드';
COMMENT ON COLUMN TB_DOC_TYPE.DOC_TYP_NM IS '문서유형명';
COMMENT ON COLUMN TB_DOC_TYPE.DOC_CAT IS '문서분류';
COMMENT ON COLUMN TB_DOC_TYPE.USE_YN IS '사용여부';

-- TB_PT_MST
COMMENT ON TABLE TB_PT_MST IS '환자 기본정보 마스터. 환자번호, 성명, 생년월일, 성별 등 인구학적 정보를 저장한다.';
COMMENT ON COLUMN TB_PT_MST.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_PT_MST.PT_NM IS '환자성명';
COMMENT ON COLUMN TB_PT_MST.BRTH_DT IS '생년월일';
COMMENT ON COLUMN TB_PT_MST.SEX_CD IS '성별코드(M/F/U)';
COMMENT ON COLUMN TB_PT_MST.RR_NO_HASH IS '주민등록번호 해시값(비식별)';
COMMENT ON COLUMN TB_PT_MST.TEL_NO IS '연락처';
COMMENT ON COLUMN TB_PT_MST.ADDR_TXT IS '주소';
COMMENT ON COLUMN TB_PT_MST.BLD_TYP IS '혈액형';
COMMENT ON COLUMN TB_PT_MST.REG_DT IS '등록일시';
COMMENT ON COLUMN TB_PT_MST.UPD_DT IS '수정일시';

-- TB_ENC_HIST
COMMENT ON TABLE TB_ENC_HIST IS '진료(Encounter) 이력. 외래/입원/응급 방문 단위의 진료 에피소드를 저장한다.';
COMMENT ON COLUMN TB_ENC_HIST.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_ENC_HIST.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_ENC_HIST.ENC_TYP IS '진료유형(O=외래,I=입원,E=응급)';
COMMENT ON COLUMN TB_ENC_HIST.ENC_STS IS '진료상태(A=재원/진행,D=종료,C=취소)';
COMMENT ON COLUMN TB_ENC_HIST.DEPT_CD IS '진료과코드';
COMMENT ON COLUMN TB_ENC_HIST.PROV_ID IS '담당의료진ID';
COMMENT ON COLUMN TB_ENC_HIST.ADM_DT IS '내원/입원일시';
COMMENT ON COLUMN TB_ENC_HIST.DSCH_DT IS '퇴원/종료일시';
COMMENT ON COLUMN TB_ENC_HIST.CHIEF_COMP IS '주소(主訴)';
COMMENT ON COLUMN TB_ENC_HIST.REG_DT IS '등록일시';

-- TB_ADM_HIST
COMMENT ON TABLE TB_ADM_HIST IS '입원 이력. Encounter 중 입원 건에 대한 병동, 병상, 입퇴원 정보를 저장한다.';
COMMENT ON COLUMN TB_ADM_HIST.ADM_ID IS '입원ID';
COMMENT ON COLUMN TB_ADM_HIST.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_ADM_HIST.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_ADM_HIST.WARD_CD IS '병동코드';
COMMENT ON COLUMN TB_ADM_HIST.BED_NO IS '병상번호';
COMMENT ON COLUMN TB_ADM_HIST.ADM_DT IS '입원일시';
COMMENT ON COLUMN TB_ADM_HIST.DSCH_DT IS '퇴원일시';
COMMENT ON COLUMN TB_ADM_HIST.DSCH_TYP IS '퇴원유형';
COMMENT ON COLUMN TB_ADM_HIST.ADM_PATH IS '입원경로';

-- TB_DGN_HIST
COMMENT ON TABLE TB_DGN_HIST IS '진단 이력. Encounter별 주진단·부진단 코드, 진단일시, 진단유형 및 진단 의료진 정보를 저장한다.';
COMMENT ON COLUMN TB_DGN_HIST.DGN_ID IS '진단이력ID';
COMMENT ON COLUMN TB_DGN_HIST.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_DGN_HIST.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_DGN_HIST.DGN_CD IS '진단코드';
COMMENT ON COLUMN TB_DGN_HIST.DGN_SEQ IS '진단순번';
COMMENT ON COLUMN TB_DGN_HIST.DGN_TYP IS '진단유형(MAIN/SUB)';
COMMENT ON COLUMN TB_DGN_HIST.ONSET_DT IS '발병일';
COMMENT ON COLUMN TB_DGN_HIST.DGN_DT IS '진단일시';
COMMENT ON COLUMN TB_DGN_HIST.PROV_ID IS '진단의료진ID';

-- TB_PROC_HIST
COMMENT ON TABLE TB_PROC_HIST IS '처치/시술 이력. Encounter에서 시행된 처치 및 시술 내역을 저장한다.';
COMMENT ON COLUMN TB_PROC_HIST.PROC_ID IS '처치이력ID';
COMMENT ON COLUMN TB_PROC_HIST.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_PROC_HIST.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_PROC_HIST.PROC_CD IS '처치시술코드';
COMMENT ON COLUMN TB_PROC_HIST.PROC_DT IS '시행일시';
COMMENT ON COLUMN TB_PROC_HIST.PROV_ID IS '시행의료진ID';
COMMENT ON COLUMN TB_PROC_HIST.DEPT_CD IS '시행진료과코드';
COMMENT ON COLUMN TB_PROC_HIST.PROC_STS IS '처치상태';
COMMENT ON COLUMN TB_PROC_HIST.RMRK_TXT IS '비고';

-- TB_ORD_HDR
COMMENT ON TABLE TB_ORD_HDR IS '오더 헤더. 검사/처방/영상 등 오더의 상위 단위를 저장한다.';
COMMENT ON COLUMN TB_ORD_HDR.ORD_NO IS '오더번호';
COMMENT ON COLUMN TB_ORD_HDR.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_ORD_HDR.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_ORD_HDR.ORD_TYP IS '오더유형(LAB/MED/IMG/PROC/ETC)';
COMMENT ON COLUMN TB_ORD_HDR.ORD_STS IS '오더상태';
COMMENT ON COLUMN TB_ORD_HDR.ORD_DT IS '오더일시';
COMMENT ON COLUMN TB_ORD_HDR.PROV_ID IS '처방의료진ID';
COMMENT ON COLUMN TB_ORD_HDR.DEPT_CD IS '처방진료과코드';
COMMENT ON COLUMN TB_ORD_HDR.REG_DT IS '등록일시';

-- TB_ORD_DTL
COMMENT ON TABLE TB_ORD_DTL IS '오더 상세. 오더 헤더에 속한 개별 오더 항목을 저장한다.';
COMMENT ON COLUMN TB_ORD_DTL.ORD_DTL_ID IS '오더상세ID';
COMMENT ON COLUMN TB_ORD_DTL.ORD_NO IS '오더번호';
COMMENT ON COLUMN TB_ORD_DTL.ORD_SEQ IS '오더순번';
COMMENT ON COLUMN TB_ORD_DTL.ORD_CD IS '오더코드';
COMMENT ON COLUMN TB_ORD_DTL.ORD_NM IS '오더명';
COMMENT ON COLUMN TB_ORD_DTL.QTY_VAL IS '수량';
COMMENT ON COLUMN TB_ORD_DTL.UNIT_CD IS '단위코드';
COMMENT ON COLUMN TB_ORD_DTL.ORD_STS IS '오더상세상태';

-- TB_LAB_ORD
COMMENT ON TABLE TB_LAB_ORD IS '임상검사 오더. 오더상세와 연계된 검체검사 요청 정보를 저장한다.';
COMMENT ON COLUMN TB_LAB_ORD.LAB_ORD_ID IS '검사오더ID';
COMMENT ON COLUMN TB_LAB_ORD.ORD_NO IS '오더번호';
COMMENT ON COLUMN TB_LAB_ORD.ORD_DTL_ID IS '오더상세ID';
COMMENT ON COLUMN TB_LAB_ORD.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_LAB_ORD.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_LAB_ORD.EXM_CD IS '검사코드';
COMMENT ON COLUMN TB_LAB_ORD.SPC_NO IS '검체번호';
COMMENT ON COLUMN TB_LAB_ORD.COLL_DT IS '채혈/검체채취일시';
COMMENT ON COLUMN TB_LAB_ORD.ORD_STS IS '검사오더상태';

-- TB_LAB_RST
COMMENT ON TABLE TB_LAB_RST IS '환자의 임상검사 결과를 저장하는 테이블. 검사결과값(문자·수치), 결과단위, 이상여부 및 결과일시를 보관한다.';
COMMENT ON COLUMN TB_LAB_RST.LAB_RST_ID IS '검사결과ID';
COMMENT ON COLUMN TB_LAB_RST.LAB_ORD_ID IS '검사오더ID';
COMMENT ON COLUMN TB_LAB_RST.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_LAB_RST.EXM_CD IS '검사코드';
COMMENT ON COLUMN TB_LAB_RST.RST_VAL IS '검사 결과값(문자)';
COMMENT ON COLUMN TB_LAB_RST.RST_NUM IS '검사 결과값(수치)';
COMMENT ON COLUMN TB_LAB_RST.RST_UNIT IS '결과단위';
COMMENT ON COLUMN TB_LAB_RST.ABN_FLG IS '이상여부(Y/N)';
COMMENT ON COLUMN TB_LAB_RST.RST_DT IS '검사 결과 일시';
COMMENT ON COLUMN TB_LAB_RST.RPT_PROV_ID IS '결과보고의료진ID';

-- TB_MED_ORD
COMMENT ON TABLE TB_MED_ORD IS '투약/처방 오더. Encounter 단위의 약품 처방 내역을 저장한다.';
COMMENT ON COLUMN TB_MED_ORD.MED_ORD_ID IS '처방오더ID';
COMMENT ON COLUMN TB_MED_ORD.ORD_NO IS '오더번호';
COMMENT ON COLUMN TB_MED_ORD.ORD_DTL_ID IS '오더상세ID';
COMMENT ON COLUMN TB_MED_ORD.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_MED_ORD.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_MED_ORD.DRUG_CD IS '약품코드';
COMMENT ON COLUMN TB_MED_ORD.DOSE_VAL IS '1회투여량';
COMMENT ON COLUMN TB_MED_ORD.DOSE_UNIT IS '투여량단위';
COMMENT ON COLUMN TB_MED_ORD.FREQ_CD IS '투여빈도코드';
COMMENT ON COLUMN TB_MED_ORD.DAYS_CNT IS '투여기간(일)';
COMMENT ON COLUMN TB_MED_ORD.ROUTE_CD IS '투여경로코드';
COMMENT ON COLUMN TB_MED_ORD.START_DT IS '투약시작일시';
COMMENT ON COLUMN TB_MED_ORD.END_DT IS '투약종료일시';
COMMENT ON COLUMN TB_MED_ORD.ORD_STS IS '처방상태';

-- TB_IMG_ORD
COMMENT ON TABLE TB_IMG_ORD IS '영상검사 오더. CT/MRI 등 영상검사 요청 정보를 저장한다.';
COMMENT ON COLUMN TB_IMG_ORD.IMG_ORD_ID IS '영상오더ID';
COMMENT ON COLUMN TB_IMG_ORD.ORD_NO IS '오더번호';
COMMENT ON COLUMN TB_IMG_ORD.ORD_DTL_ID IS '오더상세ID';
COMMENT ON COLUMN TB_IMG_ORD.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_IMG_ORD.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_IMG_ORD.IMG_CD IS '영상검사코드';
COMMENT ON COLUMN TB_IMG_ORD.ACC_NO IS 'Accession Number';
COMMENT ON COLUMN TB_IMG_ORD.ORD_DT IS '오더일시';
COMMENT ON COLUMN TB_IMG_ORD.PERF_DT IS '촬영시행일시';
COMMENT ON COLUMN TB_IMG_ORD.ORD_STS IS '영상오더상태';

-- TB_IMG_RPT
COMMENT ON TABLE TB_IMG_RPT IS '영상검사 판독문. 영상오더에 대한 소견 및 판독 결과를 저장한다.';
COMMENT ON COLUMN TB_IMG_RPT.IMG_RPT_ID IS '판독문ID';
COMMENT ON COLUMN TB_IMG_RPT.IMG_ORD_ID IS '영상오더ID';
COMMENT ON COLUMN TB_IMG_RPT.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_IMG_RPT.RPT_DT IS '판독일시';
COMMENT ON COLUMN TB_IMG_RPT.RPT_PROV_ID IS '판독의료진ID';
COMMENT ON COLUMN TB_IMG_RPT.FIND_TXT IS '소견내용';
COMMENT ON COLUMN TB_IMG_RPT.IMPR_TXT IS '판독인상(Impression)';
COMMENT ON COLUMN TB_IMG_RPT.RPT_STS IS '판독상태';

-- TB_CLN_DOC
COMMENT ON TABLE TB_CLN_DOC IS '임상문서. 퇴원요약, 경과기록 등 Encounter 단위 전자문서를 저장한다.';
COMMENT ON COLUMN TB_CLN_DOC.DOC_ID IS '문서ID';
COMMENT ON COLUMN TB_CLN_DOC.ENC_ID IS 'Encounter ID';
COMMENT ON COLUMN TB_CLN_DOC.PT_NO IS '환자번호';
COMMENT ON COLUMN TB_CLN_DOC.DOC_TYP_CD IS '문서유형코드';
COMMENT ON COLUMN TB_CLN_DOC.DOC_TTL IS '문서제목';
COMMENT ON COLUMN TB_CLN_DOC.DOC_BODY IS '문서본문';
COMMENT ON COLUMN TB_CLN_DOC.AUTH_PROV_ID IS '작성의료진ID';
COMMENT ON COLUMN TB_CLN_DOC.DOC_DT IS '작성일시';
COMMENT ON COLUMN TB_CLN_DOC.DOC_STS IS '문서상태';
