-- ============================================================
-- Indexes for medical_demo (query / analyzer metadata)
-- ============================================================

CREATE INDEX IF NOT EXISTS IX_PT_NM ON TB_PT_MST (PT_NM);
CREATE INDEX IF NOT EXISTS IX_PT_BRTH ON TB_PT_MST (BRTH_DT);

CREATE INDEX IF NOT EXISTS IX_ENC_PT ON TB_ENC_HIST (PT_NO);
CREATE INDEX IF NOT EXISTS IX_ENC_DT ON TB_ENC_HIST (ADM_DT);
CREATE INDEX IF NOT EXISTS IX_ENC_DEPT ON TB_ENC_HIST (DEPT_CD);
CREATE INDEX IF NOT EXISTS IX_ENC_TYP ON TB_ENC_HIST (ENC_TYP);

CREATE INDEX IF NOT EXISTS IX_ADM_PT ON TB_ADM_HIST (PT_NO);
CREATE INDEX IF NOT EXISTS IX_ADM_WARD ON TB_ADM_HIST (WARD_CD);

CREATE INDEX IF NOT EXISTS IX_DGN_ENC ON TB_DGN_HIST (ENC_ID);
CREATE INDEX IF NOT EXISTS IX_DGN_PT ON TB_DGN_HIST (PT_NO);
CREATE INDEX IF NOT EXISTS IX_DGN_CD ON TB_DGN_HIST (DGN_CD);
CREATE INDEX IF NOT EXISTS IX_DGN_DT ON TB_DGN_HIST (DGN_DT);

CREATE INDEX IF NOT EXISTS IX_PROC_ENC ON TB_PROC_HIST (ENC_ID);
CREATE INDEX IF NOT EXISTS IX_PROC_PT ON TB_PROC_HIST (PT_NO);

CREATE INDEX IF NOT EXISTS IX_ORD_ENC ON TB_ORD_HDR (ENC_ID);
CREATE INDEX IF NOT EXISTS IX_ORD_PT ON TB_ORD_HDR (PT_NO);
CREATE INDEX IF NOT EXISTS IX_ORD_TYP ON TB_ORD_HDR (ORD_TYP);
CREATE INDEX IF NOT EXISTS IX_ORD_DT ON TB_ORD_HDR (ORD_DT);

CREATE INDEX IF NOT EXISTS IX_ORD_DTL_NO ON TB_ORD_DTL (ORD_NO);

CREATE INDEX IF NOT EXISTS IX_LAB_ORD_ENC ON TB_LAB_ORD (ENC_ID);
CREATE INDEX IF NOT EXISTS IX_LAB_ORD_PT ON TB_LAB_ORD (PT_NO);
CREATE INDEX IF NOT EXISTS IX_LAB_ORD_EXM ON TB_LAB_ORD (EXM_CD);

CREATE INDEX IF NOT EXISTS IX_LAB_RST_PT ON TB_LAB_RST (PT_NO);
CREATE INDEX IF NOT EXISTS IX_LAB_RST_EXM ON TB_LAB_RST (EXM_CD);
CREATE INDEX IF NOT EXISTS IX_LAB_RST_DT ON TB_LAB_RST (RST_DT);

CREATE INDEX IF NOT EXISTS IX_MED_ORD_PT ON TB_MED_ORD (PT_NO);
CREATE INDEX IF NOT EXISTS IX_MED_ORD_DRUG ON TB_MED_ORD (DRUG_CD);
CREATE INDEX IF NOT EXISTS IX_MED_ORD_ENC ON TB_MED_ORD (ENC_ID);

CREATE INDEX IF NOT EXISTS IX_IMG_ORD_PT ON TB_IMG_ORD (PT_NO);
CREATE INDEX IF NOT EXISTS IX_IMG_ORD_ENC ON TB_IMG_ORD (ENC_ID);
CREATE INDEX IF NOT EXISTS IX_IMG_ORD_CD ON TB_IMG_ORD (IMG_CD);

CREATE INDEX IF NOT EXISTS IX_IMG_RPT_PT ON TB_IMG_RPT (PT_NO);
CREATE INDEX IF NOT EXISTS IX_IMG_RPT_DT ON TB_IMG_RPT (RPT_DT);

CREATE INDEX IF NOT EXISTS IX_CLN_DOC_ENC ON TB_CLN_DOC (ENC_ID);
CREATE INDEX IF NOT EXISTS IX_CLN_DOC_PT ON TB_CLN_DOC (PT_NO);
CREATE INDEX IF NOT EXISTS IX_CLN_DOC_TYP ON TB_CLN_DOC (DOC_TYP_CD);

CREATE INDEX IF NOT EXISTS IX_LAB_MST_CAT ON TB_LAB_MST (EXM_CAT);
CREATE INDEX IF NOT EXISTS IX_LAB_REF_EXM ON TB_LAB_REF (EXM_CD);
CREATE INDEX IF NOT EXISTS IX_PROV_DEPT ON TB_PROVIDER (DEPT_CD);
CREATE INDEX IF NOT EXISTS IX_CODE_GRP ON TB_CODE_MST (CD_GRP);
